# Generated by Django 2.2.2 on 2019-06-06 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='bragets',
        ),
        migrations.CreateModel(
            name='Bragets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(blank=True, null=True)),
                ('product_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bragets', to='restaurant.Products')),
            ],
        ),
    ]
