# Generated by Django 2.2.2 on 2019-06-06 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0007_auto_20190606_0613'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='product_image',
            new_name='product_image3',
        ),
    ]
