# Generated by Django 2.2.2 on 2019-06-06 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0008_auto_20190606_0614'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='product_image3',
        ),
        migrations.AddField(
            model_name='bragets',
            name='bragets',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='product_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='bragets',
            name='product_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='restaurant.Products'),
        ),
    ]
