# Generated by Django 2.2.2 on 2019-06-06 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0010_auto_20190606_0616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bragets',
            name='bragets',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
