# Generated by Django 2.2.2 on 2019-06-06 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0011_auto_20190606_0617'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='descripition',
            new_name='description',
        ),
    ]
