# Generated by Django 2.2.2 on 2019-06-06 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0013_products_fullfilled_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='addeddays',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='created',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
