# Generated by Django 2.2.2 on 2019-06-06 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0014_auto_20190606_0737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='created',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
