# Generated by Django 2.2.2 on 2019-06-06 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0015_auto_20190606_0745'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='addeddays',
        ),
        migrations.AddField(
            model_name='products',
            name='enddate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
