# Generated by Django 2.2.2 on 2019-06-06 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0016_auto_20190606_0753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='enddate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
