# Generated by Django 2.2.2 on 2019-06-06 11:22

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0019_auto_20190606_0758'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_status', models.BooleanField(blank=True, default=False, null=True)),
                ('quantity', models.PositiveIntegerField(default=0, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('product_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='restaurant.Products')),
            ],
        ),
    ]
